### ISSUE TITLE
Update build.gradle

### ISSUE THREAD

**Issue by mo22** [Crypho/react-native-scrypt#10]
Hi,

can you add the following changes to android/build.gradle?

- implementation instead of compile
- compileSdkVersion rootProject.ext.compileSdkVersion

Thank you

**Comment by ggozad** [comment]
A PR would be welcome.

**Comment by tex0l** [comment]
Why was this issue closed? It would be useful to merge #48

**Comment by tex0l** [comment]
@ggozad would it be possible to merge #48? It is actually blocking for me because the default Gradle version used in latest version of react-native isn't compatible with the current gradle build file.

**Comment by ggozad** [comment]
Hey!
I no longer work for Crypho, but will let the people who do know about this. For what is worth I approve merging #48 .

**Comment by tex0l** [comment]
Hi @ggozad,
Thank you for the quick reply! Sorry to hear you are not working for Crypho anymore. Thank you for forwarding the message :).
