### ISSUE TITLE
Documentation: Return type?

### ISSUE THREAD

**Issue by lll000111** [Crypho/react-native-scrypt#13]
What is the return type of the scrypt function?

Normally I would expect a Buffer, but since RN cannot pass binary data between native and Javascript...

Is it a string of lower case hexadecimal ([I looked here](https://github.com/Crypho/react-native-scrypt/blob/master/android/src/main/java/com/crypho/scrypt/RNScryptModule.java#L48) for Android [and here](https://github.com/Crypho/react-native-scrypt/blob/master/ios/RNScrypt.m#L57) for iOS)?

**Comment by ggozad** [comment]
Yes it is.
